Added all the required files for the project.
Abmart0803/Portfolio-Project pull request #1
Opened 2023-02-14 20:00 UTC by Abmart0803

Added the following files as per the project requirement: 
new file:  .github/workflows/linters.yml

   new file:   .gitignore
        new file:   .hintrc
        new file:   .stylelintrc.json
        new file:   LICENSE
        modified:   README.md
        new file:   images/Counter.png
        new file:   images/Linkedin icon.png
        new file:   images/angellist.png
        new file:   images/github.png
        new file:   images/header-shapes mobile.png
        new file:   images/medium.png
        new file:   images/twitter.png
        new file:   index.html
        new file:   package-lock.json
        new file:   package.json
        new file:   style.css.

2023-02-14 22:44 UTC, Owusu-Desmond requested changes
Hi @Abmart0803 , 

Good job so far!
You still need to work on some issues to go to the next project, but you are almost there!

<img src="https://media3.giphy.com/media/31Q36EHJ7C5ZoIMw79/giphy.gif"/>

## Highlights
📌 No Linters error ✅
📌 Descriptive pull request✅
📌 Great working on the setup of the project ✅
📌 Good commit messages ✅
📌 Professional README file ✅

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-14 22:44 UTC, Owusu-Desmond commented on index.html
> +    </div>
- [ ] Please make sure that the logo has a link (a tag). This is for three reasons: convention, semantics, and user experience(UX). [Check this link](https://ux.stackexchange.com/questions/81727/why-is-it-standard-for-a-website-logo-to-navigate-to-the-home-page) for more info. :pray:

2023-02-14 22:44 UTC, Owusu-Desmond commented on README.md
> +### Author1
- [ ] Please let's fix this grammar error, since you are the only contributor to this project you can singularize the `Authors` to `Author` and replace `Author1` with your name. :smile:

2023-02-15 07:27 UTC, Tadesse-Alemayehu approved these changes
### Hi @Abmart0803 

### I'm Tadesse Alemayehu your reviewer for this PR. :hand: 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
![giphy (1)](https://user-images.githubusercontent.com/69077061/212969210-69f495ba-f2fb-4559-a222-d1507310d6fb.gif)

## Highlights
 - [ ] Good job making the changes requested by the previous code reviewer. ✅

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-15 07:27 UTC, Tadesse-Alemayehu commented on index.html
>      </div>
- [Optional] Good job making your navigation a link. But while you do so I notice your styles are getting lost. I suggest looking through your nav-logo, maybe setting the `font-size: 2rem` would be great.

2023-02-20 11:05 UTC, merged