Add window-popup
Abmart0803/Portfolio-Project pull request #14
Opened 2023-03-08 14:57 UTC by Abmart0803

Added window-popup to the project.

2023-03-08 16:04 UTC, AnselemOdims requested changes
### Hi @Abmart0803 , 
You have been doing a tremendous job so far :ok_hand:
There are some issues that you still need to work on to go to the next project but you are almost there!

## To Highlight 🎉
PR has a title and summary. :heavy_check_mark:
No linter errors :heavy_check_mark:

## Required Changes ♻️
- [ ] Please also check inline comments under the review

## Optional suggestions
_Comments with the [OPTIONAL] prefix are not a must to implement however, It's strongly recommended to work on them as they can make your code better._

## Happy coding!👏👏👏

#### Please leave any questions or comments in the PR if you have any doubts or unclarity! You can tag me using @AnselemOdims for a quicker response

**_Note: Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2023-03-08 16:04 UTC, AnselemOdims commented on index.html
> +  </section>
- [ ] Also, for the works section, please ensure the card images are reversed just as it is in the original design

### Your Design
![image](https://user-images.githubusercontent.com/43995830/223764642-945f0fce-5462-41ba-b99a-d6b07298d2f5.png)

### Original Design
![image](https://user-images.githubusercontent.com/43995830/223764410-bec04f52-63fc-45eb-a75e-391a49b56df6.png)

2023-03-08 19:52 UTC, huseyinbiyik requested changes
Hi team,

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.
![tenor](https://user-images.githubusercontent.com/25887253/205415161-00e79d1b-af68-4f10-9b2c-265f460dc5da.gif)

 ## Highlights
- Pair work 👍 👍 
- Github flow followed 👌
- .gitignore used to ignore requested files 📁


 ## Required Changes ♻️

_Check the comments under the review._

## Optional suggestions
- Unfortunately, the previous reviewer didn't notice that you have no linters for JavasScript. So I need to keep it optional. As you did on the previous mobile navigation project, please add a linter for [HTML&CSS&JavaScript.](https://github.com/microverseinc/linters-config/tree/master/html-css-js)

-  Please make sure your commit messages are meaningful and descriptive for your next commits. Use imperative tense and capitalize the first word. For example, 
👌"Add logo to navigation bar"
👌"Fix close button functionality on mobile navbar"
❌ "Added logo to navigation bar"
❌ "Added HTML"
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-08 19:52 UTC, huseyinbiyik commented on index.html
> +  </section>
Unfortunately, while you are fixing issues requested from the previous reviewer, you introduced new bugs.
- On the mobile version of the popup, images and button are overflowing from the card. 
<img width="391" alt="Screenshot 2023-03-08 at 10 26 12 PM" src="https://user-images.githubusercontent.com/25887253/223824659-c20e333d-a8e8-482e-b23a-6fd0b97ae912.png">
<img width="391" alt="Screenshot 2023-03-08 at 10 26 18 PM" src="https://user-images.githubusercontent.com/25887253/223824670-da96548e-35d8-4d8d-a9ee-989886cc7b92.png">

- Some cards, not the popup windows lost their border and layout after your last commit like below. 
<img width="391" alt="Screenshot 2023-03-08 at 10 23 18 PM" src="https://user-images.githubusercontent.com/25887253/223824894-db210ab7-a3b5-4576-bf1c-bd27fd3dad69.png">

- [OPTIONAL] Since the previous reviewer didn't notice I will keep it optional but there is an horizontal overflowing issue on mobile version.
![Screen Recording 2023-03-08 at 10 23 35 PM](https://user-images.githubusercontent.com/25887253/223825146-e738446a-2246-400f-886d-c5adc4d1d371.gif)

2023-03-08 19:52 UTC, huseyinbiyik commented on index.html
> +          <img class="connect" src="./image/LET’S CONNECT.png" alt="connect">
[OPTIONAL] I think this needs be text instead of image because you can see it has font and color values 👍 
<img width="900" alt="Screenshot 2023-03-08 at 10 36 38 PM" src="https://user-images.githubusercontent.com/25887253/223825589-72d3caea-e852-4dc5-9bea-daf004229170.png">

2023-03-09 13:01 UTC, levy002 reviewed
## Hello @Abmart0803 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request :red_circle: :red_circle: 

You have submitted a project, that:

 - [ ] Doesn't run all linters check. Kindly make sure the linter runs to check the errors in your codebase.
 - [ ] has a conflict with the `master` branch. Kindly make sure to solve the conflict and submit your project again.

    
    ![image](https://user-images.githubusercontent.com/87197412/224030606-d6815277-3d05-412c-ba12-a7a659d12c98.png)

 
Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-03-09 13:40 UTC, closed without merging