Adding desktop version of the project.
Abmart0803/Portfolio-Project pull request #4
Opened 2023-02-22 21:13 UTC by Abmart0803

Modify the index.html file and styles.css file as a result of adding the desktop version of the project.

2023-02-22 22:05 UTC, Abenezer-Tilahun requested changes
Hi @Abmart0803  , 

Great job for implemented  the suggested changes , but there are some changes that need to be implemented in order to proceed to the next project 👍

## Highlights 👏🏻

✔️ No Linters error
✔️ You used correct Git Hub-Flow.
✔️ Good commit messages
✔️ Professional READEME 


![almost](https://user-images.githubusercontent.com/65860678/170491251-b1add8ba-b18f-4648-a893-20e510d957fd.gif)

## Required Changes ♻️
_Check the comments below the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-22 22:05 UTC, Abenezer-Tilahun commented on style.css
>  }
- [ ] As stated in the project requirement You must replicate the design as much as possible (e.g., font, colors, images, text, margins) using [the info from the Figma templates](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=0%3A1), So kindly Fix the below design issues
- Your Desktop Headline section (Kindly adjust the section background image it's not responsive,  Adjust the alignment of the The text and social media icon links )

![Capture](https://user-images.githubusercontent.com/93598189/220767154-baa540eb-898d-40a0-b7f2-a84e521402ff.PNG)

- The Figma design Headline section 
![Capture](https://user-images.githubusercontent.com/93598189/220767571-b29bb4a7-c9d9-40bc-8893-8e6570d887f2.PNG)

- For the Work section (Kindly fix the button just like the Figma design), Kindly I recommend you to implemented the button interaction , 
![Capture](https://user-images.githubusercontent.com/93598189/220768321-f1501688-fcce-4e2a-a102-14bb21d7156a.PNG)

- For The About section (Kindly adjust the font size of the "Let's connect" and the position of the social icons Just like the Figma design the social icons are above the button "Get Resume").
![Capture](https://user-images.githubusercontent.com/93598189/220769205-94ff4ebc-be50-4078-bd69-b6a739c2631a.PNG)

Your About Section Look likes this : 
![Capture](https://user-images.githubusercontent.com/93598189/220769396-757c059d-b2be-4985-b95c-854c89ce8e4a.PNG)

- For The contact section (Kindly adjust the section background just like the Figma design . it 's not responsive )
![Capture](https://user-images.githubusercontent.com/93598189/220769904-99b67c0f-ddc4-4cb3-bb17-5f72fc36c3b6.PNG)

- The Figma design contact section Look likes this : 
![Capture](https://user-images.githubusercontent.com/93598189/220770134-87511929-d6a0-4e72-9111-1ab2e441708f.PNG)

2023-02-24 12:42 UTC, souad988 requested changes
Hi @Abmart0803 , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![212385281-4797c58a-d358-423a-aa7c-832c22203865](https://user-images.githubusercontent.com/59707859/221181375-f13724e9-a8fb-456a-8603-f73d2d4de152.gif)


 ## Highlights
✔No linter errors
✔Good use of github workflow

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-24 12:42 UTC, souad988 commented on index.html
> +      <section>
well done by making some of the changes requested by the previous reviewer 💪, **Only** your background image still needs to be aligned as requested before 

![background image position](https://user-images.githubusercontent.com/59707859/221179272-5986bc44-e40d-4954-b2db-25a7c5a826a7.PNG)

2023-02-24 12:42 UTC, souad988 commented on index.html
> +      <section class="project-section">
Also good job in this section the buttons in the cards have the same hover effect as in the template 👍, but some cards doesn't have a border and the background is not the same please check the images bellow and make sure to replicate the figma design 

**figma work section cards :**

![work section background figma](https://user-images.githubusercontent.com/59707859/221180174-976deb45-06bd-4192-8b89-dee1f72c94b0.PNG)

**your work section cardss :**

![Uploading cards without border.PNG…]()

2023-02-24 12:42 UTC, souad988 commented on index.html
> +            action="https://formspree.io/f/xeqdybag"
Good job here as well your desktop version looks good in this section but the mobile one is not as expected, adding responsiveness to a web page means that both mobile and desktop size should have a good looking design, kindly fix this small issue and your project will be ready for the approval 

![student contact me](https://user-images.githubusercontent.com/59707859/221181221-c7734e57-d41c-4f17-ae60-da7dc1a3c54d.PNG)

2023-02-25 14:20 UTC, didierganthier requested changes
Hi @Abmart0803  ,

🎉 Great job on addressing the feedback from the previous review! You've made some solid progress in implementing the requested changes. However, there are still a few areas that need some attention before we can move on to the next project.

<img src="https://media.giphy.com/media/3oEduMcvxTNPlGuhH2/giphy.gif" />

## Highlights
- Descriptive PR ✔️ 
- Linters passing ✔️ 
- Correct GitHub flow ✔️ 

## Required Changes 🛠
- Please review the comments under the review for specific changes that still need to be made.

## Optional Suggestions 💡
- While these comments with the [OPTIONAL] prefix won't prevent the approval of this pull request, I strongly recommend taking them into account as they can improve your code. Some of them were missed by the previous reviewer and addressing them will really enhance your application.

🚀 Keep pushing forward, you're almost there! If you have any questions or need clarification on anything, feel free to leave a comment in the pull request thread and don't forget to tag me so I'll receive the notification.

**Please note**
- To avoid confusion and delays, please do not open a new pull request for re-reviews. Use the same pull request submitted for the first review, unless otherwise instructed.

------
As per the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561), you have a limited number of reviews per project. If you feel that the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s). 

Cheers and happy coding! 👏👏👏

2023-02-25 14:20 UTC, didierganthier commented on index.html
> +      <section>
I see that you tried to fix this 👍🏽 but while trying to do that, you introduced a new issue on the desktop 🖥️ version. The `header` section is too close to the `works` one, I think this can be fixed by adding more spacing between the elements in this section. This is what you have for now 👇🏽 
![Screenshot 2023-02-25 at 08 56 33](https://user-images.githubusercontent.com/45739963/221360838-66d70d1a-0b3e-4187-9144-5b76d19057c0.png)

2023-02-25 14:20 UTC, didierganthier commented on index.html
> +    </header>
[OPTIONAL] This is optional 🤷🏽 as this was not mentioned previously but there's some margin when I'm resizing the screen 💻 Take a look below 👇🏽 
![Screenshot 2023-02-25 at 09 03 50](https://user-images.githubusercontent.com/45739963/221361153-d31fd3b6-95a9-48ef-a60e-e93165cc7538.png)

Also, look to position your Logo at the extreme right of the screen, you can do that by giving the logo and the nav container a `display: flex`, `flex-direction: row` and `justify-content: space-between;`

2023-02-25 18:05 UTC, GedeonTS requested changes
# STATUS: CHANGES REQUIRED :recycle: :
Hi @Abmart0803 , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

<img src="https://media.giphy.com/media/31Q36EHJ7C5ZoIMw79/giphy.gif">

 ## Highlights :tophat: :+1: 
- No linter errors :+1: 
- Good use of GitHub flow :+1: 

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions :ringed_planet: 

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-25 18:05 UTC, GedeonTS commented on index.html
> +                    <a href="https://twitter.com/MartinsAbmart">
- [ ] As requested by the previous reviewer, I suggest increasing the space between the headline section and the work section to stick to the Figma design:
- [OPTIONAL] I suggest using the right background image for the desktop version in order to stick the Figma design :recycle:


Your design:
![Screenshot from 2023-02-25 19-56-57](https://user-images.githubusercontent.com/97834160/221372558-455f90c8-763c-4a96-a7c3-c8400200bd56.png)
Figma:
![Screenshot from 2023-02-25 20-04-01](https://user-images.githubusercontent.com/97834160/221372626-ab6e6566-4c43-4b3d-9d71-bcaafaad56cf.png)

2023-02-25 18:50 UTC, OyePriscilla requested changes
Hi @Abmart0803 👍, 

Great work on making the changes requested by a previous reviewer 👏 

You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![so-close-so-close-seth-meyers](https://user-images.githubusercontent.com/103386183/196425724-8ca5825c-b02a-4983-b976-4bd0a2f70f9a.gif)

 ## Highlights
Linters passed ✔️ 
Use CSS media query technique ✔️ 

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-25 18:50 UTC, OyePriscilla commented on index.html
> +                    <a href="https://twitter.com/MartinsAbmart">
- [ ] I observed you've tried to implement the changes required by the last reviewer, but because the **project-section** has the same `background-color` with the **headline section**; the changes is not obvious. You can choose to add the line of code to your CSS file in order to achieve this. ℹ️ 

- [optional] Kindly try and increase the margin between the project cards (**.project-card**), in order to have a design close to figma. 👍 


> .project-section {
  background-color: #DFE1E6;
}

2023-02-25 19:52 UTC, souad988 approved these changes
Hi @Abmart0803 , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
✔Correct github flow
✔No linter errors

## Optional suggestions
_Please make sure to fix the get my resume button as it has a shadow without any interaction also the button comes before social media icons , kindly fix these issues before  you start working on next projects work 

**your project :**
![SHADOW](https://user-images.githubusercontent.com/59707859/221376859-d7d31911-9889-4d1f-bc1a-fc00541b7415.PNG)

**figma :**
![shadow figma](https://user-images.githubusercontent.com/59707859/221376909-bff39093-731f-4fb6-b135-35104482bffe.PNG)

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-25 19:58 UTC, merged